execute as @a[tag=air,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^2 ^10 if entity @e[type=build:square,family=4x4,r=8,c=1] run fill ~2 ~2 ~2 ~-2 ~-2 ~-2 air
execute as @a[tag=air,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^4 ^20 if entity @e[type=build:square,family=8x8,r=16,c=1] run fill ~4 ~4 ~4 ~-4 ~-4~-4 air
execute as @a[tag=air,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^5 ^30 if entity @e[type=build:square,family=10x10,r=20,c=1] run fill ~5 ~5 ~5 ~-5 ~-3 ~-5 air
execute as @a[tag=air,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^10 ^50 if entity @e[type=build:square,family=20x20,r=40,c=1] run fill ~10 ~10 ~10 ~-10 ~-10 ~-10 air
execute as @a[tag=sandstone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^2 ^10 if entity @e[type=build:square,family=4x4,r=8,c=1] run fill ~2 ~2 ~2 ~-2 ~-2 ~-2 sandstone
execute as @a[tag=sandstone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^4 ^20 if entity @e[type=build:square,family=8x8,r=16,c=1] run fill ~4 ~4 ~4 ~-4 ~-4~-4 sandstone
execute as @a[tag=sandstone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^5 ^30 if entity @e[type=build:square,family=10x10,r=20,c=1] run fill ~5 ~5 ~5 ~-5 ~-3 ~-5 sandstone
execute as @a[tag=sandstone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^10 ^50 if entity @e[type=build:square,family=20x20,r=40,c=1] run fill ~10 ~10 ~10 ~-10 ~-10 ~-10 sandstone
execute as @a[tag=water,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^2 ^10 if entity @e[type=build:square,family=4x4,r=8,c=1] run fill ~2 ~2 ~2 ~-2 ~-2 ~-2 water
execute as @a[tag=water,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^4 ^20 if entity @e[type=build:square,family=8x8,r=16,c=1] run fill ~4 ~4 ~4 ~-4 ~-4~-4 water
execute as @a[tag=water,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^5 ^30 if entity @e[type=build:square,family=10x10,r=20,c=1] run fill ~5 ~5 ~5 ~-5 ~-3 ~-5 water
execute as @a[tag=water,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^10 ^50 if entity @e[type=build:square,family=20x20,r=40,c=1] run fill ~10 ~10 ~10 ~-10 ~-10 ~-10 water
execute as @a[tag=stone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^2 ^10 if entity @e[type=build:square,family=4x4,r=8,c=1] run fill ~2 ~2 ~2 ~-2 ~-2 ~-2 stone
execute as @a[tag=stone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^4 ^20 if entity @e[type=build:square,family=8x8,r=16,c=1] run fill ~4 ~4 ~4 ~-4 ~-4~-4 stone
execute as @a[tag=stone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^5 ^30 if entity @e[type=build:square,family=10x10,r=20,c=1] run fill ~5 ~5 ~5 ~-5 ~-3 ~-5 stone
execute as @a[tag=stone,hasitem=[{item=card:square,location=slot.weapon.mainhand}]] at @s positioned ^ ^10 ^50 if entity @e[type=build:square,family=20x20,r=40,c=1] run fill ~10 ~10 ~10 ~-10 ~-10 ~-10 stone
