tag @s remove tcard01
tag @s remove tcard02
tag @s remove tcard03
tag @s remove tcard04
tag @s remove tcard05
tag @s remove tcard06
tag @s remove tcard07
tag @s remove tcard08
tag @s remove tcard09
tag @s remove tcard10