execute as @e[family=map1] at @s run particle map:all ~0.5 ~ ~
execute if score UnlockMapLvl quest matches 0..0 as @e[family=map1] at @s run particle map:clouds_all ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 1..1 as @e[family=map1] at @s run particle map:clouds_1 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 2..2 as @e[family=map1] at @s run particle map:clouds_2 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 3..3 as @e[family=map1] at @s run particle map:clouds_3 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 4..4 as @e[family=map1] at @s run particle map:clouds_4 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 5..5 as @e[family=map1] at @s run particle map:clouds_5 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 6..6 as @e[family=map1] at @s run particle map:clouds_6 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 7..7 as @e[family=map1] at @s run particle map:clouds_7 ~0.7 ~ ~
execute if score UnlockMapLvl quest matches 8..8 as @e[family=map1] at @s run particle map:clouds_8 ~0.7 ~ ~